Lab 01 - Number in Range
-

Using try-catch block to control the program flow. If the number can't be parsed to int or the number is out of range, 
a new NumberFormatException is thrown and the appropriate message is displayed on the console. When number is successfully 
parsed to an int and also in the range, the program ends and a message with the valid number is displayed. 